version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vendorbridge-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ARRv7055
      POSTGRES_DB: vendorbridge
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
